version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5432:5432"
    networks: 
      - rede-softplan

  spring:
    image: alkarramax/spring-boot
    container_name: spring
    ports: 
      - "8080:8080"
    depends_on: 
      - postgres
    networks: 
      - rede-softplan
  
  react:
    image: alkarramax/react-app
    container_name: react
    ports: 
      - "3000:80"
    depends_on: 
      - spring
    networks: 
      - rede-softplan

networks:
  rede-softplan:
          driver: bridge
       
